// AUTO-GENERATED by scripts/figma-batch-clone.mjs
// Source clientId: lyonsplumbingheating
// Edit this file for per-client refinements.

export const siteConfig = {
  business_name: "Lyons Plumbing & Heating Ltd",
  trade: "Plumber",
  location: "Manchester, Greater Manchester",
  phone: "07912 093167",
  whatsapp_number: "447912093167",
  tagline: "Reliable Gas Safe Plumbing & Heating in Manchester.",
  est_year: "2021",
  accent_colour: "#1565C0",
  instagram_handle: "lyonsplumbingltd",
  logo_path: "/images/lyons-logo.png",
  gas_safe_badge_logo: "/images/gas-safe-register.png",
  gas_safe_licence_no: "508830",
  use_hero_image: false,
  google_place_id: "",
  // PLACEHOLDER - replace with direct Google Business Profile reviews URL.
  reviews_url: "https://www.google.com/search?q=Lyons+Plumbing+Heating+Manchester+reviews",
  map_embed_url: "https://www.google.com/maps?q=5+Greenhaven+Cl,+Walkden,+Worsley,+Manchester+M28+3TX&z=17&output=embed",

  hero_image: "/images/projects/gasassured-hero.jpg",
  about_image: "/images/projects/gasassured-hero.jpg",

  services_list: [
  {
    "icon": "Hammer",
    "name": "Boiler installation and servicing",
    "description": "Boiler installs, replacements and annual servicing to keep your heating reliable and efficient all year round."
  },
  {
    "icon": "Home",
    "name": "Central heating installation",
    "description": "Full central heating systems designed and fitted for consistent warmth, better performance and lower running issues."
  },
  {
    "icon": "PaintBucket",
    "name": "Gas Safe repairs",
    "description": "Gas Safe fault finding and repairs carried out quickly and safely, with clear advice before any work starts."
  },
  {
    "icon": "DoorOpen",
    "name": "Bathroom plumbing",
    "description": "Bathroom plumbing for upgrades, refits and repairs including pipework, showers, taps and sanitary connections."
  },
  {
    "icon": "Fence",
    "name": "Landlord gas safety certificates",
    "description": "Landlord gas safety checks and certification completed on time, with straightforward reporting for compliance."
  },
  {
    "icon": "Wrench",
    "name": "Emergency plumbing",
    "description": "Responsive emergency plumbing for urgent leaks, breakdowns and heating issues when you need help fast."
  }
],

  // PLACEHOLDER - replace with real Lyons Plumbing & Heating project photos.
  gallery_images: [
  "/images/projects/boiler-install.jpg",
  "/images/projects/radiator-replacement.jpg",
  "/images/projects/system-flush.jpg",
  "/images/projects/gas-hob-install.jpg",
  "/images/projects/full-heating-system.jpg",
  "/images/projects/plumbing-work.jpg"
],

  // PLACEHOLDER - replace with real Lyons Plumbing & Heating Instagram images.
  instagram_feed: [
  "/images/projects/boiler-install.jpg",
  "/images/projects/radiator-replacement.jpg",
  "/images/projects/system-flush.jpg",
  "/images/projects/gas-hob-install.jpg",
  "/images/projects/full-heating-system.jpg",
  "/images/projects/plumbing-work.jpg"
],

  about_text: [
  "Lyons Plumbing & Heating Ltd supports homeowners and landlords across Manchester with reliable plumbing, heating and Gas Safe work.",
  "As a growing local Ltd business, we focus on clear quotes, tidy workmanship and dependable service from first call to completion."
],

  testimonials: [
  {
    "quote": "Thank you to all that helped to fit our new bathroom! Great customer service and great job done. Would highly recommend Lyons Plumbing & Heating Ltd.",
    "name": "Samantha",
    "location": "Manchester"
  },
  {
    "quote": "Really pleased with my new bathroom! Turned out better than I imagined. Would 100% recommend. Thanks so much - tidy workers, lovely people!",
    "name": "Katie",
    "location": "Manchester"
  },
  {
    "quote": "Brilliant job on my bathroom, would highly recommend the team. Very clean and tidy and a first class fit. Thank you.",
    "name": "Neil",
    "location": "Manchester"
  }
],
};
